
services:
  n8n:
    image: n8nio/n8n
    container_name: n8n-master
    restart: always
    ports:
      - "5678:5678"
    environment:
      # This is the URL used by n8n to connect to itself for webhooks
      WEBHOOK_URL: http://localhost:5678/
    volumes:
      - .:/home/node/.n8n

volumes:
  n8n_data:
