services:
  n8n:
    image: n8nio/n8n
    container_name: n8n-master
    user: "1000:1000"
    restart: always
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=http://localhost:5678/
      # Add the line below to disable the login screen
      - N8N_USER_MANAGEMENT_DISABLED=true
    volumes:
      - .:/home/node/.n8n

volumes:
  n8n_data: